[build]
  base = "Frontend/"
  publish = "build"
  command = "yarn run setup-netlify && yarn run build"

[build.environment]
  INLINE_RUNTIME_CHUNK = false
  
[[redirects]]
  from = "/sitemap.xml"
  to = "$REACT_APP_BACKEND_URL/sitemap"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
