[build]
  base = "Frontend/"
  publish = "build"
  command = "yarn run setup-netlify && yarn run build"

[[redirects]]
  from = "/sitemap.xml"
  to = "$REACT_APP_BACKEND_URL/sitemap"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
