language: csharp
dotnet: 1.1.5
mono: none
dist: trusty
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
services:
  - docker
script:
  - dotnet restore CollAction
  - dotnet build CollAction -c Release
  - dotnet publish CollAction -c Release
after_success:
  - chmod +x scripts/docker-push.sh
  - scripts/docker-push.sh
  