language: csharp
dotnet: 2.0.0
mono: none
dist: trusty
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce awscli
services:
- docker
script:
- dotnet restore CollAction
- dotnet build CollAction -c Release
- dotnet publish CollAction -c Release
after_success:
- chmod +x scripts/docker-push.sh
- scripts/docker-push.sh
env:
  global:
  - secure: mq+UswcnMptlRDGuJqflzBJkrNdClrle6iSBPOLVHUv2zlqc6xgUPnjou35yndO7Kn5ynz+GQVJI2hO+uJ+UPXr9GOfPLtBRa/QI1jqHm6+0OL9hwYDGwBDlrgyvWeHH4wWGPEBAldyqp9wRyNKEsiVPXqJ5sK81FRMHkbi0ODRN8D6uEu18a/H4sYGi4t1FtmwVsM5iVn0hRsH7FOsFmF3uTmNfk1Os/964Vr6DHv9w9MoMrA/uwiyrMmoZgas8DC2J2UMQRDEyaq/OyJEF+tGjDG4ofb6UcbaQ3ODvkL24jVYyavOCHPuPeaFi8d9HlcXpDCKRgRAKc1d/ufhsFsNaSIRwbs7fQ2B5VtFPmhzciq/5i9onH5DGll1YxweWALKlgz5NkCiHawjxm8Q7/iR9xB7gF+L/vqQYcHbL/3gEKZwNtrFYPt9yjZo/3ytj3dHeJNInToe5mKIEXKfoDTJY2pBHnEpsnv7YEEcKv4h/S4AfzqQ1g1G3hzmopSLCPGaUpAUBcDTjHjxAWhLTTTFVvAkjrMr+v4p991AOyhYHZ5OVgslMeo1mDGeBlej7BRQhvJRvMrbIm87DWT2oPhcLKeeLDVyrCBBM2wuZQNEFSEYvI/RBzFQC4tpTmAJHJMjj4OoKTFJNgPCyi8cYr4jyYz+D52oxFbDqVsEVfxo=
  - secure: d7oo2dd9u3+IugpUlV13YnYEYf10YxBN/3TVUhf/FXsqs6gHl3uSlITsGgoujxnJwztCe8clinj1Yo/Oz7/REEshnHEkm+M2djn6zvQ6HqSAdDoQt9AkzV7/TC6sYEs0c70mFlRYmG7atVnr34hU2rrgv6J3Giq1/JniSxR/nMaNdFzAzz/X/WMxme0TRqKeWiT7894oCxRxQQow7/NdeeXaQXJ/reDgfEiyMfjuRqWWaULbLiuKBM5vrj2d0SXkADXpVQc3l5H/Q7zuag9NHmZPCtdaJtcMtzIDAJ2jw06+OtF4rr23+CNB2S1PKv7vywPzAiPJvQs6UfP5uWFf8ArusyR74zmn1XkybeiQQYya5MNX9s1zGdB2nPAtRZ1LvVkBDIMBU9L465zX7ggoVJU2p/+1cR5rryVM/qTvmZoQiDVD+LEFnGB8n77WgWtYG2g4I00ZkiM8OjFv+hllPhEx/rjrUYRf/aVL1yo7oLZP8cHuua6A7zmhZQCYyYqVSbGtE1utqwF1TQc7pGqQHvwJBG741ODDY8+GyKR/7RIQgNunhBzh08LuazqsbK4nr4WTdN+HI11FnTOb0bXBkzPmve6cSYz2RatEO4Bm17P3HYdRW6B0okXNFMg5Kb1EHpVV33GR8i+ksr07JP28p690gq4P/vi2gzusi0dsOVg=
