language: csharp
dotnet: 2.0.0
mono: none
dist: trusty
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
services:
  - docker
script:
  - dotnet restore CollAction
  - dotnet publish CollAction -c Release -o bin/netcoreapp/publish
after_success:
  - chmod +x scripts/docker-push.sh
  - scripts/docker-push.sh
  