version: '3.4'

services:
  backend:
    image: collaction-backend
    build:
      context: .
      dockerfile: CollAction/Dockerfile
      args:
        BUILD_CONFIG: Debug
    env_file:
      - env_collaction
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "44301:44301"
    environment:
      - PublicAddress=http://localhost:8000;http://localhost:3000
      - DbHost=db
      - DbUser=postgres
      - DbPassword=test
      - Db=CollActionDb
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:44301
      - Kestrel__Certificates__Default__Path=/app/collaction.pfx
      - Kestrel__Certificates__Default__Password=test

  frontend:
    image: collaction-frontend
    build:
      context: Frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=https://localhost:44301
    ports:
      - "8000:8000"

  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CollActionDb
    ports:
      - "5432:5432"