version: '3.4'

volumes:
  images:

services:
  backend:
    image: collaction-backend
    build:
      context: .
      dockerfile: CollAction/Dockerfile
      args:
        WITH_TEST_SSL: 1
    env_file:
      - env_collaction
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "44301:44301"
    environment:
      - DbHost=db
      - PublicAddress=http://localhost:8000
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:44301
      - Kestrel__Certificates__Default__Path=/app/collaction.pfx
      - Kestrel__Certificates__Default__Password=test

  frontend:
    image: collaction-frontend
    build:
      context: Frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    links:
      - backend:backend
    ports:
      - "8000:80"

  db:
    image: postgres
    env_file:
      - env_postgres
    ports:
      - "5432:5432"