version: '2'

services:
  backend:
    image: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - env_backend
    depends_on:
      - db
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: postgres
    env_file:
      - env_postgres
    ports:
      - "5432:5432"