version: '2'

volumes:
  images:

services:
  collaction:
    image: collaction
    build:
      context: ./CollAction
      dockerfile: Dockerfile
    env_file:
      - env_collaction
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "5000:5000"
    volumes:
      - images:/app/wwwroot/usercontent
      - "./CollAction:/app"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
    command: "run"

  collaction-frontend:
    image: collaction-frontend
    build:
      context: ./CollAction
      dockerfile: Dockerfile.frontend
    volumes:
      - "./CollAction:/app"

  db:
    image: postgres
    env_file:
      - env_postgres
    ports:
      - "5432:5432"
