[build]
  base = "Frontend/"
  publish = "Frontend/build"
  command = "yarn run setup-netlify && cat $REACT_APP_BACKEND_URL && cat ../netlify.toml && yarn run build"

[build.environment]
  INLINE_RUNTIME_CHUNK = "false"
  
[[redirects]]
  from = "/sitemap.xml"
  to = "$REACT_APP_BACKEND_URL/sitemap"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none';"
    Content-Security-Policy = '''
      block-all-mixed-content; 
      upgrade-insecure-requests; 
      object-src 'self'; 
      form-action 'self' https://*.list-manage.com/ https://*.collaction.org https://api.twitter.com https://accounts.google.com https://www.facebook.com; 
      connect-src 'self' https://*.collaction.org https://www.linkedin.com/ https://linkedin.com/ https://www.twitter.com/ https://twitter.com/ https://www.facebook.com/ https://facebook.com/ https://graph.facebook.com/ https://api.stripe.com https://www.google-analytics.com; 
      img-src 'self' data: https://www.google-analytics.com https://*.s3.eu-central-1.amazonaws.com; 
      style-src 'self' https://fonts.googleapis.com/ 'unsafe-inline'; 
      font-src 'self' https://fonts.googleapis.com/ https://fonts.gstatic.com; 
      media-src 'self'; 
      frame-src 'self' https://js.stripe.com https://hooks.stripe.com https://www.youtube-nocookie.com/; 
      script-src 'self' https://www.google-analytics.com https://js.stripe.com; 
      frame-ancestors 'none'
    '''

[[headers]]
  for = "/widget/*"
  [headers.value]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none';"
    Content-Security-Policy = '''
      block-all-mixed-content; 
      upgrade-insecure-requests; 
      object-src 'self'; 
      form-action 'self' https://*.list-manage.com/ https://*.collaction.org https://api.twitter.com https://accounts.google.com https://www.facebook.com; 
      connect-src 'self' https://*.collaction.org https://www.linkedin.com/ https://linkedin.com/ https://www.twitter.com/ https://twitter.com/ https://www.facebook.com/ https://facebook.com/ https://graph.facebook.com/ https://api.stripe.com https://www.google-analytics.com; 
      img-src 'self' data: https://www.google-analytics.com https://*.s3.eu-central-1.amazonaws.com; 
      style-src 'self' https://fonts.googleapis.com/ 'unsafe-inline'; 
      font-src 'self' https://fonts.googleapis.com/ https://fonts.gstatic.com; 
      media-src 'self'; 
      frame-src 'self' https://js.stripe.com https://hooks.stripe.com https://www.youtube-nocookie.com/; 
      script-src 'self' https://www.google-analytics.com https://js.stripe.com; 
      frame-ancestors 'none'
    '''
