backend:
  name: github
  repo: CollActionteam/CollAction
  branch: CA-707
media_folder: Frontend/static/assets
public_folder: assets
collections:
  - name: about
    label: About page
    description: Content blocks for the site's about page
    files:
      - name: mission
        label: Mission statement
        delete: false
        file: Frontend/src/content/about/mission.md
        fields:
          - { name: type, default: about, widget: hidden }
          - { name: content, label: Mission statement, widget: markdown }
      - name: about
        label: About CollAction
        delete: false
        file: Frontend/src/content/about/about.md
        fields:
          - { name: type, default: about, widget: hidden }
          - { name: content, label: About CollAction, widget: markdown }
      - name: team
        label: Meet the team
        file: Frontend/src/content/about/team.yml
        delete: false
        fields:
          - name: team
            label: Team members
            widget: list
            fields:
              - { name: name, label: Name, widget: hidden }
              - { name: photo, label: Photo, widget: image }
      - name: join
        label: Join the team
        delete: false
        file: Frontend/src/content/about/join.md
        fields:
          - { name: type, default: about, widget: hidden }
          - { name: content, label: Join the team, widget: markdown }
      - name: partners
        label: Partners
        delete: false
        file: Frontend/src/content/about/partners.md
        fields:
          - { name: type, default: about, widget: hidden }
          - { name: content, label: Partners, widget: markdown }

  - name: blogs
    label: Blog posts
    description: Entries created here will appear on the blogs page.
    folder: Frontend/src/content/blogs
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields: 
      - { name: type, default: blogpost, widget: hidden }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Content, widget: markdown }
