backend:
  name: github
  repo: CollActionteam/CollAction
  branch: CA-707
media_folder: Frontend/static/assets
public_folder: assets
collections:
  - name: about
    label: About page
    description: Content blocks for the site's about page
    folder: Frontend/src/content/about
    create: false
    delete: false
    fields:
      - { name: type, default: about, widget: hidden }
      - { name: name, widget: hidden }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Content, widget: markdown }

  - name: team
    label: Team overview
    delete: false
    files:
      - label: Meet the team
        name: team
        file: Frontend/src/content/about/team.yml
        fields:
          - { name: title, label: Title, widget: string }
          - name: team
            label: Team members
            widget: list
            fields:
              - { name: name, label: Name, widget: string }
              - { name: photo, label: Photo, widget: image }

  - name: blogs
    label: Blog posts
    description: Entries created here will appear on the blogs page.
    folder: Frontend/src/content/blogs
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields: 
      - { name: type, default: blogs, widget: hidden }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Content, widget: markdown }
