backend:
  name: github
  repo: CollActionteam/CollAction
  branch: CA-707
media_folder: Frontend/static/assets
public_folder: assets
collections:
  - name: about
    label: About page
    description: Content blocks for the site's about page
    files:
      - name: mission
        label: Mission statement
        delete: false
        file: Frontend/src/content/about/mission.md
        fields:
          - { name: mission, label: Mission statement, widget: markdown }

      - name: team
        label: Meet the team
        file: Frontend/src/content/about/team.yml
        delete: false
        fields:
          - name: team
            label: Team members
            widget: list
            fields:
              - { name: name, label: "Name", widget: string }
              - { name: photo, label: "Photo", widget: image }

  - name: blogs
    label: Blog posts
    description: Entries created here will appear on the blogs page.
    folder: Frontend/src/content/blogs
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields: 
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Content, widget: markdown }
