backend:
  name: github
  repo: CollActionteam/CollAction
  branch: CA-707
media_folder: Frontend/static/assets
public_folder: assets
collections:
  - name: blogs
    label: Blog posts
    folder: Frontend/src/content/blogs
    slug: "{{ year }}-{{ month }}-{{ day }}-{{ slug }}"
    create: true
    fields: 
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Content, widget: markdown }
  # - name: blog
  #   label: Blog
  #   folder: Frontend/src/content/blog
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   preview: true
  #   create: true
  #   fields:
  #     - { name: date, label: Date, widget: date }
  #     - { name: title, label: Title }
  #     - { name: body, label: Body, widget: markdown }
