backend:
  name: github
  repo: CollActionteam/CollAction
  branch: CA-707
media_folder: Frontend/static/assets
public_folder: assets
collections:
  - name: home_content
    label: Home page content
    folder: Frontend/src/content/home
    create: false
    delete: false
    fields:
      - { name: type, default: home, widget: hidden }
      - { name: name, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Content, widget: markdown }

  - name: home_settings
    label: Home page settings
    delete: false
    files:
      - label: Photos
        name: photos
        file: Frontend/src/content/home/photos.yml
        fields:
          - { name: name, default: photos, widget: hidden }
          - { name: bannertitle, label: Banner title, widget: string }
          - { name: bannerphoto, label: Banner photo, widget: image }
      - label: Crowdacting Steps
        name: crowdacting_steps
        file: Frontend/src/content/home/crowdacting-steps.yml
        fields:
          - { name: name, default: crowdactingsteps, widget: hidden }
          - { name: title, label: Title, widget: string }
          - label: Steps
            name: steps
            widget: list
            fields:
              - { label: Photo, name: photo, widget: image }
              - { label: Title, name: name, widget: string }
              - { label: Body, name: body, widget: markdown }

  - name: about_content
    label: About page content
    description: Content blocks for the site's about page
    folder: Frontend/src/content/about
    create: false
    delete: false
    fields:
      - { name: type, default: about, widget: hidden }
      - { name: name, widget: hidden }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Content, widget: markdown }

  - name: about_settings
    label: About page settings
    delete: false
    files:
      - label: Videos
        name: videos
        file: Frontend/src/content/about/video.yml
        fields:
          - { name: name, default: videos, widget: hidden }
          - { name: mainvideo, label: Main video, hint: Link to YouTube video, widget: string }

      - label: Meet the team
        name: team
        file: Frontend/src/content/about/team.yml
        fields:
          - { name: name, default: team, widget: hidden }
          - { name: title, label: Title, widget: string }
          - name: team
            label: Team members
            widget: list
            fields:
              - { name: name, label: Name, widget: string }
              - { name: photo, label: Photo, widget: image }

  - name: blogs
    label: Blog posts
    description: Entries created here will appear on the blogs page.
    folder: Frontend/src/content/blogs
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields: 
      - { name: type, default: blogs, widget: hidden }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Content, widget: markdown }
