backend:
  name: github
  repo: CollActionteam/CollAction
  branch: CA-707
media_folder: Frontend/static/assets
public_folder: assets
collections:
  - name: blogs
    label: Blog posts
    description: Entries created here will appear on the blogs page.
    folder: Frontend/src/content/blogs
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields: 
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Content, widget: markdown }
