backend:
  name: github
  repo: CollActionteam/CollAction
  branch: CA-707
media_folder: Frontend/static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: Frontend/src/content/blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview: true
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
