backend:
  name: github
  repo: CollActionteam/CollAction
  branch: CA-707
media_folder: Frontend/static/assets
public_folder: assets
collections:
  - name: home_content
    label: Home page content
    folder: Frontend/src/content/home
    create: false
    delete: false
    fields:
      - { name: type, default: home, widget: hidden }
      - { name: name, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Content, widget: markdown }

  - name: home_settings
    label: Home page settings
    delete: false
    files:
      - label: Photos
        name: photos
        file: Frontend/src/content/home/photos.yml
        fields:
          - { name: name, default: photos, widget: hidden }
          - { name: bannertitle, label: Banner title, widget: string }
          - { name: bannerphoto, label: Banner photo, widget: image }

  - name: startproject_content
    label: Start project page content
    folder: Frontend/src/content/startproject
    create: false
    delete: false
    fields:
      - { name: type, default: start, widget: hidden }
      - { name: name, widget: string }
      - { name: body, label: Content, widget: markdown }

  - name: startproject_settings
    label: Start project page settings
    delete: false
    files:
      - label: Photos
        name: photos
        file: Frontend/src/content/startproject/photos.yml
        fields:
          - { name: name, default: photos, widget: hidden }
          - { name: startprojectphoto, label: Banner photo, widget: image }

  - name: startproject_steps
    identifier_field: name
    label: Steps to start a project
    folder: Frontend/src/content/startproject/steps
    create: true
    delete: true
    fields:
      - { name: type, default: startprojectsteps, widget: hidden }
      - { name: sequence, label: Sequence, widget: number, hint: Use "0" for the introduction text. }
      - { name: name, widget: string }
      - { name: image, label: Image, widget: image, required: false, hint: Image is not supported for the introduction text (sequence 0) }
      - { name: body, label: Content, widget: markdown }

  - name: crowdacting_steps
    label: Crowdacting steps
    folder: Frontend/src/content/crowdactingsteps
    create: true
    delete: true
    fields:
      - { name: type, default: crowdactingsteps, widget: hidden }
      - { name: sequence, label: Sequence, widget: number }
      - { name: name, widget: string }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Content, widget: markdown }

  - name: find_content
    label: Find page content
    folder: Frontend/src/content/find
    create: false
    delete: false
    fields:
      - { name: type, default: find, widget: hidden }
      - { name: name, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Content, widget: markdown }

  - name: find_settings
    label: Find page settings
    delete: false
    files:
      - label: Photos
        name: photos
        file: Frontend/src/content/find/photos.yml
        fields:
          - { name: name, default: photos, widget: hidden }
          - { name: bannerphoto, label: Banner photo, widget: image }

  - name: about_content
    label: About page content
    description: Content blocks for the site's about page
    folder: Frontend/src/content/about
    create: false
    delete: false
    fields:
      - { name: type, default: about, widget: hidden }
      - { name: name, widget: hidden }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Content, widget: markdown }
      
  - name: about_settings
    label: About page settings
    delete: false
    files:
      - label: Videos
        name: videos
        file: Frontend/src/content/about/video.yml
        fields:
          - { name: name, default: videos, widget: hidden }
          - { name: mainvideo, label: Main video, hint: Link to YouTube video, widget: string }

      - label: Meet the team
        name: team
        file: Frontend/src/content/about/team.yml
        fields:
          - { name: name, default: team, widget: hidden }
          - { name: title, label: Title, widget: string }
          - name: team
            label: Team members
            widget: list
            fields:
              - { name: name, label: Name, widget: string }
              - { name: photo, label: Photo, widget: image }

  - name: about_faq
    label: About page FAQs
    identifier_field: name
    description: Frequently asked questions on the site's about page
    folder: Frontend/src/content/about/faq
    create: true
    delete: true
    fields:
      - { name: type, default: about_faq, widget: hidden }
      - { name: name, label: Title, widget: string }
      - { name: sequence, label: Sequence, widget: number }
      - { name: body, label: Content, widget: markdown }

  - name: blogs
    label: Blog posts
    description: Entries created here will appear on the blogs page.
    folder: Frontend/src/content/blogs
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields: 
      - { name: type, default: blogs, widget: hidden }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Content, widget: markdown }
