name: .NET Core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Db: CollActionDb
      DbUser: postgres
      DbPassword: test
      DbHost: localhost
      FromAddress: hello@collaction.org

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: postgres
          POSTGRES_DB: CollActionDb

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal