name: .NET Core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1-buster

    env:
      Db: CollActionDb
      DbUser: postgres
      DbPassword: test
      DbHost: postgres
      FromAddress: hello@collaction.org
      MailChimpTestListId: 1a035c45ca
      S3Region: eu-central-1
      S3Bucket: collaction-test
      SesRegion: eu-west-1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      MailChimpKey: ${{ secrets.MailChimpKey }}
      S3AwsAccessKeyId: ${{ secrets.S3AwsAccessKeyId }}
      S3AwsAccessKey: ${{ secrets.S3AwsAccessKey }}
      SesAwsAccessKeyId: ${{ secrets.SesAwsAccessKeyId }}
      SesAwsAccessKey: ${{ secrets.SesAwsAccessKey }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: $DbPassword
          POSTGRES_USER: $DbUser
          POSTGRES_DB: $Db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-restore