name: Build Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
        repository: collaction/backend
        tag_with_ref: true
        dockerfile: CollAction/Dockerfile