name: On Push

on: 
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*  # Not on version tags

jobs:
  test_backend:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1-buster

    env:
      Db: CollActionDb
      DbUser: postgres
      DbPassword: test
      DbHost: postgres
      FromAddress: hello@collaction.org
      MailChimpTestListId: 1a035c45ca
      S3Region: eu-central-1
      S3Bucket: collaction-test
      SesRegion: eu-west-1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      MailChimpKey: ${{ secrets.MailChimpKey }}
      S3AwsAccessKeyId: ${{ secrets.S3AwsAccessKeyId }}
      S3AwsAccessKey: ${{ secrets.S3AwsAccessKey }}
      SesAwsAccessKeyId: ${{ secrets.SesAwsAccessKeyId }}
      SesAwsAccessKey: ${{ secrets.SesAwsAccessKey }}
      Authentication__Facebook__AppId: ${{ secrets.Authentication__Facebook__AppId }}
      Authentication__Facebook__AppSecret: ${{ secrets.Authentication__Facebook__AppSecret }}
      Authentication__Google__ClientId: ${{ secrets.Authentication__Google__ClientId }}
      Authentication__Google__ClientSecret: ${{ secrets.Authentication__Google__ClientSecret }}
      Authentication__Twitter__ConsumerKey: ${{ secrets.Authentication__Twitter__ConsumerKey }}
      Authentication__Twitter__ConsumerSecret: ${{ secrets.Authentication__Twitter__ConsumerSecret }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: postgres
          POSTGRES_DB: CollActionDb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-restore

  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
        repository: collaction/frontend
        tag_with_ref: true
        dockerfile: Frontend/Dockerfile
        path: Frontend 

  build_backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
        repository: collaction/backend
        tag_with_ref: true
        dockerfile: CollAction/Dockerfile