name: On Push

on:
  push:
    tags:
      - 'v*' # Push events matching v*, e.g. v2.0.0.

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
        repository: collaction/frontend
        tag_name: ${{ github.ref }}
        dockerfile: Frontend/Dockerfile
        path: Frontend

  build_backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
        repository: collaction/backend
        tag_name: ${{ github.ref }}
        dockerfile: CollAction/Dockerfile