name: Deploy to staging

on: 
  push:
    branches:
      - master

jobs:
  deploy_backend_master:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Determine image tag
      id: get_imagetag
      run: echo ::set-output name=TAG::sha-${GITHUB_SHA:12}    

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
        repository: collaction/backend
        tags: ${{ steps.get_imagetag.outputs.TAG }},latest
        dockerfile: CollAction/Dockerfile

    - uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

    - name: Terraform Init
      working-directory: ./Terraform/staging
      run: terraform init

    - name: Terraform Format
      working-directory: ./Terraform/staging
      run: terraform fmt -check

    - name: Terraform Plan
      working-directory: ./Terraform/staging
      run: terraform plan -var "imageversion=${{ steps.get_imagetag.outputs.TAG }}"
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      

    - name: Terraform Apply
      working-directory: ./Terraform/staging
      run: terraform apply -auto-approve -var "imageversion=${{ steps.get_imagetag.outputs.TAG }}"
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      
